# Generated by Django 5.1.1 on 2024-10-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0008_rename_owner_listitem_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='image',
            field=models.ImageField(
                blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
