# Generated by Django 5.1.1 on 2024-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0010_alter_listitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='image',
            field=models.JSONField(default=list),
        ),
    ]
