# Generated by Django 5.1.1 on 2024-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0011_alter_listitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplist',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='grouplist',
            name='user_id_string',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
