# Generated by Django 5.1.1 on 2024-11-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0013_remove_listitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
