# Generated by Django 5.1.1 on 2024-11-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0014_listitem_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
