# Generated by Django 5.1.1 on 2024-11-06 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0018_remove_grouplist_user_id_string'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplist',
            name='list_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='shared_with', to='lista.listitem'),
        ),
        migrations.AlterField(
            model_name='grouplist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='group_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
