# Generated by Django 5.1.1 on 2024-11-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0020_remove_listitem_images_listitemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitemimage',
            name='image',
            field=models.ImageField(
                blank=True, default='/placeholder.png', null=True, upload_to='list_item_images/'),
        ),
    ]
