# Generated by Django 5.1.1 on 2024-11-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0028_recommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFace',
        ),
    ]
