# Generated by Django 5.1.1 on 2024-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='listitem',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
