# Generated by Django 5.1.1 on 2024-10-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_grouplist_user_alter_listitem_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='owner',
            new_name='user_id',
        ),
    ]
