# Generated by Django 5.1.1 on 2024-11-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_user_grouplist_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='image',
        ),
    ]
