# Generated by Django 5.1.1 on 2024-11-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_user_id_listitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
