# Generated by Django 5.1.1 on 2024-11-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_listitem_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplist',
            old_name='user_id',
            new_name='user',
        ),
    ]
