# Generated by Django 5.1.1 on 2024-11-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_user_id_grouplist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplist',
            name='user_id_string',
        ),
    ]
